server:
  port: 9090

spring:
  application:
    name : drs-system

    jpa:
      hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        ddl-auto: update
        properties:
          hibernate:
            dialect: org.hibernate.dialect.SQLServerDialect


  datasource:
    url: jdbc:sqlserver://103.74.65.45;databaseName=DealerRevenueScorecard;encrypt=true;trustServerCertificate=true;
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver


#    spring.datasource.url= jdbc:sqlserver://localhost:1434;encrypt=true;trustServerCertificate=true;databaseName=bezkoder_db



